[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
abi_stable = "0.10.4"
# cglue = {version = "0.2.5", features = ["layout_checks"] }

